### ISSUE TITLE
Module Not Found Error :coordShift.json

### ISSUE THREAD

**Issue by jmjff** [ATR-DBI/CityRefer#11]
hi, when I run prepare_data.py ,I meet an error:
![image](https://github.com/ATR-DBI/CityRefer/assets/129597090/57930651-95a7-4126-bbf9-8f8441f1e3f2)
I cannot find this coordShift.json

**Comment by miyatai2** [comment]
The pre-processing script was updated.

**Comment by Rabbia-Hassan** [comment]
hello,
I am getting this issue I think due to CoordSHif.json file issue. Can you please guide?
![image](https://github.com/user-attachments/assets/0a2052af-a714-4b85-a060-4e21a85efc8c)
because it looks like this,
![image](https://github.com/user-attachments/assets/cbb6191f-f4cd-44e6-aea1-785b5e9def0b)

thanks

**Comment by Rabbia-Hassan** [comment]
@jmjff , how did you solve this problem? there is no coordShift.json file there 
@miyatai2
