### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './balance_split/random-50_crop-250/val_val_250m/coordShift.json'

### ISSUE THREAD

**Issue by Chunmian-art** [ATR-DBI/CityRefer#8]
FileNotFoundError: [Errno 2] No such file or directory: './balance_split/random-50_crop-250/val_val_250m/coordShift.json'

Can you release the coordShift.json in this code?

**Comment by miyatai2** [comment]
I fixed the pre-processing script.

**Comment by Rabbia-Hassan** [comment]
hello,
I am getting this issue I think due to CoordSHif.json file issue. Can you please guide?
![image](https://github.com/user-attachments/assets/0a2052af-a714-4b85-a060-4e21a85efc8c)
because it looks like this,
![image](https://github.com/user-attachments/assets/cbb6191f-f4cd-44e6-aea1-785b5e9def0b)

thanks
